### ISSUE TITLE
Issue with make tb_toolchain

### ISSUE THREAD

**Issue by jacksonrbarlow** [EIE2-IAC-Labs/Lab0-devtools#3]
When running the command, a part of the text at the end is missing (single-float ABI) I'm not sure whether this is a library that needs installing or something else

![image](https://user-images.githubusercontent.com/115641372/195362229-bfd7e0c3-d839-4545-a0af-5e7503ff0b2c.png)

**Comment by Jpnock** [comment]
I agree this is a bit odd!

However, you'd normally get a compilation error if this option was actually missing from the compiler rather than it compiling successfully. So I think this should be fine to ignore.
