### ISSUE TITLE
Unable to start debug

### ISSUE THREAD

**Issue by ZZZ02zk** [EIE2-IAC-Labs/Lab0-devtools#8]
![屏幕截图 2022-10-16 212546](https://user-images.githubusercontent.com/115665668/196056573-0d6ea977-1c42-4f56-9b48-0ad85e2aee23.png)
I ran the test, the system still reports that I need to verify the MI debugger. 
I already try the code but it still not working. 
 "MIMode": "gdb",
 "miDebuggerPath": "/usr/bin/gdb"

**Comment by Jpnock** [comment]
Debugging with F5 under gdb is not supported for the labs, so this is not expected to work.

As long as you can run `make tb_verilator` and `make tb_toolchain` in the VS Code terminal (not anywhere else) then everything is set up correctly. (I believe you contacted me on Teams and we made sure that worked there).

Let us know if you encounter any other problems
