### ISSUE TITLE
Full build not completed due to error on Ubuntu OS 22.04

### ISSUE THREAD

**Issue by IlanIwumbwe** [EIE2-IAC-Labs/Lab0-devtools#9]
![image](https://github.com/EIE2-IAC-Labs/Lab0-devtools/assets/56346800/0a0d82ee-8736-4b99-8201-278dd056df45)

Shown above is my terminal output. Looking at the terminal output in Issue #4, the full build isn't complete, which explains the missing verilator files in my workspace. However, I am not sure why the build stops as above, presumably because of my Latex editor.

**Comment by IlanIwumbwe** [comment]
Debugged this myself by looking at shell script

**Comment by pykc** [comment]
> Looking at the ubuntu shell script, this fails while trying to run 'sudo apt-get update'. That particular repo doesn't have a release for my distro, so I removed it from my list of repositories. All is working now

I am glad that this is resolved. Well done.

**Comment by IlanIwumbwe** [comment]
Thank you
